# Generated by Django 4.1.3 on 2022-11-21 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_cinema_description_alter_room_seat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="seat",
        ),
        migrations.AddField(
            model_name="seat",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="movie.room",
            ),
        ),
    ]
