# Generated by Django 4.1.3 on 2022-11-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_remove_room_seat_seat_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="cinema",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cinema",
                to="movie.room",
            ),
        ),
    ]
