# Generated by Django 4.1.3 on 2022-11-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_cinema_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinema",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="cinema",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room",
                to="movie.cinema",
            ),
        ),
    ]
