# Generated by Django 4.1.3 on 2022-11-21 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_remove_cinema_room_room_cinema"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="type_ticket",
        ),
        migrations.AddField(
            model_name="typeticket",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typeticket",
                to="movie.ticket",
            ),
        ),
    ]
