# Generated by Django 4.1.3 on 2022-11-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0006_remove_ticket_type_ticket_typeticket_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.RemoveField(
            model_name="typeticket",
            name="ticket",
        ),
        migrations.AddField(
            model_name="ticket",
            name="typeticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="movie.typeticket",
            ),
        ),
        migrations.AddField(
            model_name="typeticket",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.seat",
            ),
        ),
    ]
