# Generated by Django 4.1.3 on 2022-11-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0007_remove_ticket_price_remove_typeticket_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
