# Generated by Django 4.1.3 on 2022-11-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0009_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.session",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payTicket",
                to="movie.user",
            ),
        ),
    ]
