# Generated by Django 4.1.3 on 2022-11-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0010_ticket_session_alter_session_time_alter_ticket_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="ticket",
        ),
        migrations.AddField(
            model_name="ticket",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ticketbook",
                to="movie.book",
            ),
        ),
    ]
