# Generated by Django 4.1.3 on 2022-11-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0011_remove_book_ticket_ticket_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="total_sum",
        ),
    ]
