# Generated by Django 4.1.3 on 2022-11-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0012_remove_book_total_sum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="room",
        ),
        migrations.RemoveField(
            model_name="session",
            name="room",
        ),
        migrations.AddField(
            model_name="room",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movie.session",
            ),
        ),
    ]
