# Generated by Django 4.1.3 on 2022-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movie.genre'),
        ),
    ]
