# Generated by Django 4.1.3 on 2022-11-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0021_discount_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.CharField(choices=[('THREE', '-3%'), ('FIVE', '-5%'), ('SEVEN', '-7%'), ('NINE', '-9%')], default=0, max_length=5),
        ),
    ]
