# Generated by Django 4.1.3 on 2022-11-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0022_user_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discount',
        ),
    ]
