# Generated by Django 4.1.3 on 2022-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0025_ticket_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(null=True, verbose_name='#'),
        ),
    ]
