# Generated by Django 4.1.3 on 2022-11-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_book_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
