# Generated by Django 4.1.3 on 2022-11-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_remove_ticket_quantity_alter_book_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.AlterField(
            model_name='book',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
